const data = [
  {
    id: 1,
    name: "İstanbul",
    img: "https://cdn.pixabay.com/photo/2020/02/23/12/22/river-4873198__340.jpg",
    desc: "İstanbul, Türkiye'de Marmara Bölgesi'nin Çatalca-Kocaeli Bölümü'nde yer alan şehir ve Türkiye'nin 81 ilinden biridir. Ülkenin nüfus bakımından en çok göç alan ve en kalabalık ilidir. Ekonomik, tarihî ve sosyo-kültürel açıdan önde gelen şehirlerden biridir.Şehir, iktisadi büyüklük açısından dünyada 34. sırada yer alır. Nüfuslarına göre şehirler listesinde belediye sınırları göz önüne alınarak yapılan sıralamaya göre Avrupa'da birinci, dünyada ise altıncı sırada yer almaktadır.  İstanbul Türkiye'nin kuzeybatısında, Marmara kıyısı ve Boğaziçi boyunca, Haliç'i de çevreleyecek şekilde kurulmuştur. İstanbul kıtalararası bir şehir olup, Avrupa'daki bölümüne Avrupa Yakası veya Rumeli Yakası, Asya'daki bölümüne ise Anadolu Yakası veya Asya Yakası denir. Tarihte ilk olarak üç tarafı Marmara Denizi, Boğaziçi ve Haliç'in sardığı bir yarımada üzerinde kurulan İstanbul'un batıdaki sınırını İstanbul Surları oluşturmaktaydı. Gelişme ve büyüme sürecinde surların her seferinde daha batıya ilerletilerek inşa edilmesiyle dört defa genişletilen şehrin 39 ilçesi vardır. Sınırları içerisinde ise büyükşehir belediyesi ile birlikte toplam 40 belediye bulunmaktadır. Dünyanın en eski şehirlerinden biri olan İstanbul, 330-395 yılları arasında Roma İmparatorluğu, 395-1204 yılları arasında Bizans İmparatorluğu, 1204-1261 yılları arasında Latin İmparatorluğu,1261-1453 yılları arasında tekrar Bizans İmparatorluğu ve son olarak 1453-1922 yılları arasında Osmanlı İmparatorluğu'na başkentlik yaptı. Ayrıca İstanbul, Hilâfetin Osmanlı İmparatorluğu'na geçtiği 1517'den kaldırıldığı 1924'e kadar İslam dünyasının da merkezi oldu.",
    more: "https://tr.wikipedia.org/wiki/%C4%B0stanbul",
  },
  {
    id: 2,
    name: "Ankara",
    img: "https://cdn.pixabay.com/photo/2014/10/03/11/11/monument-471329__340.jpg",
    desc: "Ankara , Türkiye'nin başkenti ve İstanbul'dan sonra en kalabalık ikinci ilidir. Nüfusu 2023 yılı itibarıyla 5.782.285 kişidir. Bu nüfus; 25 ilçe ve bu ilçelere bağlı 1425 mahallede yaşamaktadır. İl genelinde nüfus yoğunluğu 215'tir. Nüfuslarına göre şehirler listesinde belediye sınırları göz önüne alınarak yapılan sıralamaya göre dünyada ise elli yedinci sırada yer almaktadır. Coğrafi olarak Türkiye'nin merkezine yakın bir konumda bulunur ve Batı Karadeniz Bölgesi'nde kalan kuzey kesimleri hariç, büyük bölümü İç Anadolu Bölgesi'nde yer alır. Yüzölçümü olarak Konya ve Sivas'tan sonra, Türkiye'nin en büyük üçüncü ilidir. Bolu, Çankırı, Kırıkkale, Kırşehir, Aksaray, Konya ve Eskişehir illeri ile çevrilidir.",
    more: "https://tr.wikipedia.org/wiki/Ankara",
  },
  {
    id: 3,
    name: "Aydın",
    img: "https://davincitur.com/uploads/0000/19/2022/12/22/aydin-kapak.jpg",
    desc: "Aydın, Türkiye'nin bir ili ve en kalabalık yirminci şehridir. Ege Bölgesi'nde yer alan, turizm ve tarım açısından en gelişmiş illerdendir. Kuzeyinde İzmir, kuzeydoğusunda Manisa, doğusunda Denizli, güneyinde Muğla illeri, batısında Ege Denizi bulunmaktadır. 2022 itibarıyla 1.134.031 kişilik nüfusuyla Ege Bölgesi'nin üçüncü büyük ilidir. 17 ilçesi vardır.",
    more: "https://tr.wikipedia.org/wiki/Ayd%C4%B1n",
  },
  {
    id: 4,
    name: "Sinop",
    img: "https://cdn.pixabay.com/photo/2022/02/11/13/01/sea-7007316__340.jpg",
    desc: "Sinop, Türkiye'nin Karadeniz Bölgesi'nin batı karadeniz bölümünde bulunan Sinop ili'nin merkezi olan şehirdir. Karadeniz kıyısında, Boztepe Burnu'nun karayla birleşme noktasında yer alır. Sinop Kalesi, tarihi ve turizm açısından kentin en ilginç yeridir. Türkiye'nin kuzeyde en uç noktası olan İnce burun Sinop ilinde'dir.",
    more: "https://tr.wikipedia.org/wiki/Sinop",
  },
  {
    id: 5,
    name: "Diyarbakır",
    img: "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/1766000/diyarbakir-iha-1766380.jpg",
    desc: "Diyarbakır , Türkiye'nin Güneydoğu Anadolu Bölgesi'nde bulunan bir şehirdir. İlin yüzölçümü 15.168 km2'dir. Valiliğin denizden yüksekliği 660 m'dir. Adıyaman, Batman, Bingöl, Elazığ, Mardin, Muş, Malatya ve Şanlıurfa illeri ile komşudur. 17 tane ilçeye sahiptir. Üzerinde tarihi Diyarbakır Kalesi'nin bulunduğu Dicle Nehri kıyısında yüksek bir plato çevresinde yer alan şehir, Türkiye'nin Güneydoğu Anadolu Bölgesi'nin yüzölçümü bakımından Şanlıurfa'dan sonraki ikinci büyük şehridir. Karasal iklimin hâkim olduğu şehirde yazlar son derece sıcak ve kurak geçer iken, kışlar ise soğuk, sert ve yağışlı geçer. Diyarbakır, yaklaşık 9000 yıllık tarihi bir geçmişe sahiptir.",
    more: "https://tr.wikipedia.org/wiki/Diyarbak%C4%B1r",
  },
  {
    id: 6,
    name: "Bursa",
    img: "https://www.bursaogretmenevi.com.tr/wp-content/uploads/2020/09/bursa-merkez-gezilecek-yerler-755x350.jpg",
    desc: "Bursa, Türkiye'nin bir ili ve en kalabalık dördüncü şehri. 2021 itibarıyla 3.147.818[2] nüfusa sahiptir. Marmara Bölgesinin Güney Marmara bölümünde, 40° kuzey enlem ve 29° doğu boylam daireleri arasında yer alır. Eski adı Hüdavendigâr'dır. Kuzeyinde Marmara Denizi ve Yalova, kuzeydoğuda Kocaeli ve Sakarya, doğuda Bilecik, güneyde Kütahya ve batıda Balıkesir illeri ile çevrilidir. Ekonomik açıdan Türkiye'nin en gelişmiş kentlerinden biri olan Bursa doğal ve tarihsel zenginlikleriyle de önem taşır. Bursa'da en çok Osmanlı İmparatorluğu'nun kuruluş dönemine ait tarihi eserlerin bulunmasının sebebi ise, Bursa'nın Osmanlı Devletinin ilk başkenti olmasıdır.",
    more: "https://tr.wikipedia.org/wiki/Bursa",
  },
  {
    id: 7,
    name: "Erzurum",
    img: "https://i4.hurimg.com/i/hurriyet/75/770x0/606997767af5072cec12e653.jpg",
    desc: "Erzurum, Türkiye'nin 81 ilinden biridir. Erzurum Ovası'nın güneydoğu kenarında, bu ova ile Palandöken dağının temas sahasında kurulmuş olan Erzurum şehri, 758.279  nüfusu ile Doğu Anadolu Bölgesi'nin en büyük üçüncü ilidir. Denizden yüksekliği yaklaşık 1900 m olan Erzurum, tarihin ilk dönemlerinden beri yerleşim yeridir. Şehir, tarihî eserleri ve kış sporları tesisleriyle de tanınır. Yüzölçümü bakımından Türkiye'nin en büyük dördüncü ili olan Erzurum'da, temel geçim kaynağı tarım ve hayvancılık olup şehir son yıllarda kış turizmiyle de öne çıkmaktadır. Soğuk iklimi sebebiyle sanayisi gelişmemiştir. 25.005 km² yüzölçümüne sahip il arazisinin %15,17'si tarımsal amaçlı olarak kullanılabilir konumdadır.",
    more: "https://tr.wikipedia.org/wiki/Erzurum",
  },
  {
    id: 8,
    name: "Bitlis",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Bitlis_view.jpg/1200px-Bitlis_view.jpg",
    desc: "Bitlis , Bitlis ilinin merkezi olan şehirdir. Merkez ilçeye bağlı üç bucak vardır. Doğu Anadolu Bölgesi'nde yer alan Bitlis'i, güneyden Siirt, batıdan Muş, kuzeyden Ağrı illeri ve doğudan Van Gölü çevreler. Bitlis, Kaleleri ve İslam eserleriyle önemli bir ildir.",
    more: "https://tr.wikipedia.org/wiki/Bitlis",
  },
  {
    id: 9,
    name: "Antalya",
    img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/50/70/c5/harbour-from-lift.jpg?w=600&h=400&s=1",
    desc: "Antalya, Türkiye'nin bir ili ve en kalabalık beşinci şehridir. 2021 sonu itibarıyla il nüfusu 2.619.832'dir. Özellikle yaz aylarında turist sayısı artar. Türkiye'de 'turizmin başkenti' olarak görülmektedir. Şehrin yüzölçümü 20.177 km2dir. İlde km2ye 130 kişi düşmektedir. En kalabalık ilçesi 2021 yılı itibarıyla 591.895 kişiyle Kepez ilçesidir. Nüfus yoğunluğunun en fazla olduğu ilçe ise km2 başına 5429 kişi ile Muratpaşa ilçesidir. 19 ilçe ve belediye, bu belediyelerde toplam 914 mahalle bulunmaktadır. Tamamı Akdeniz Bölgesi'nin batısında yer alır ve Antalya Körfezi'yle Batı Torosların arasında kurulmuştur. Yüzölçümü bakımından Türkiye'nin beşinci büyük ilidir. Güneyinde Akdeniz, batısında Muğla, kuzeyinde Burdur ve Isparta, kuzeydoğusunda Konya, doğusunda ise Karaman ve Mersin illeri vardır.",
    more: "https://tr.wikipedia.org/wiki/Antalya",
  },
  {
    id: 10,
    name: "Bolu",
    img: "https://i20.haber7.net/resize/1280x720//haber/haber7/photos/2020/15/boluda_gezilecek_yerler_listesi_10_farkli_adres_1586701032_772.jpg",
    desc: "Bolu, Bolu ilinin merkez ilçesi ve aynı adlı bir şehirdir. Türkiye yüz ölçümünün %1,015'lik bölümünü kaplayan Bolu ili, 8.323 km² yüz ölçümü ile Karadeniz Bölgesi’nin Batı Karadeniz bölümünde yer alır. İl arazisinin yaklaşık %18’ini tarım alanları oluşturmaktadır. Orman alanları ise %64’lük bir oran ile Türkiye ormanları içinde %2,55’lik paya sahiptir. Çayır ve meraların kapladığı alan yaklaşık %15’tir. Geriye kalan %8 dolayında alan ise tarım dışı alanlardır.    Ortalama rakım 1000 m, merkez ilçe rakımı ise 725 m civarındadır. Matematiksel konum açısından 30 derece 32 dakika - 32 derece 36 dakika Doğu boylamları ile 40 derece 06 dakika - 41 derece 01 dakika Kuzey enlemleri arasındadır.",
    more: "https://tr.wikipedia.org/wiki/Bolu",
  },
  {
    id: 11,
    name: "Trabzon",
    img: "https://im.haberturk.com/2021/06/22/ver1624361235/3111775_810x458.jpg",
    desc: "Trabzon , Türkiye'nin bir ili ve en kalabalık yirmi yedinci şehridir. TÜİK verilerine göre ise Trabzon’un 2021 nüfusu 816.684 oldu. Erkeklerin nüfusu 405 Bin 47, kadınların nüfusu ise 411 Bin 637 dir. Karadeniz Bölgesi'nin Doğu Karadeniz Bölümü'nde yer alan ilin Karadeniz'e kıyısı bulunur. Karadeniz sahili ile Doğu Karadeniz Dağları arasında yer almakta olup yüzölçümü açısından az bir alan kaplar. Batısında Giresun'a bağlı Eynesil ilçesi, güneyinde Gümüşhane'ye bağlı Torul ilçesi ve Bayburt, doğusunda da Rize'ye bağlı İkizdere ve Kalkandere ilçeleri bulunur.",
    more: "https://tr.wikipedia.org/wiki/Trabzon",
  },
  {
    id: 12,
    name: "Mardin",
    img: "https://imgs.platinonline.com/Documents/Platin/images/2021/03/17/17032021161593842413f89c43.jpg",
    desc: "Mardin, Türkiye'nin büyükşehir statüsüne giren bir ili ve en kalabalık yirmi altıncı şehridir. 2021 yılı TÜİK verilerine göre nüfusu 862.757’dir. Güneydoğu Anadolu Bölgesi'nin Dicle Bölümü'nde yer alır. Suriye ile sınır komşusudur. Şehirde uluslararası kuruluşlarca kültür mirası kabul edilmiş, koruma altına alınmış tarihi yapılar mevcuttur. Mardin farklı dini inanışlar paralelinde, sanatsal açıdan da tarihi değeri olan camiler, türbeler, kiliseler, manastır ve benzeri dini eserler barındırmaktadır. Mardin, İpek Yolu güzergâhında olup, ilde beş han ve bir kervansaray mevcuttur.",
    more: "https://tr.wikipedia.org/wiki/Mardin",
  },
  {
    id: 13,
    name: "İzmir",
    img: "http://jackroaming.com/wp-content/uploads/2021/11/Best-Things-to-do-in-Izmir-Turkey-featured-Izmir-Clock-Tower.jpg",
    desc: "İzmir, Türkiye'de Ege Bölgesi'nde yer alan şehir ve ülkenin 81 ilinden biridir. Ülkenin nüfus bakımından en kalabalık üçüncü şehridir. Ekonomik, tarihi ve sosyo-kültürel açıdan önde gelen şehirlerden biridir. Nüfusu 2022 itibarıyla 4.462.056 kişidir. Yüzölçümü olarak ülkenin yirmi üçüncü büyük ilidir. Etrafı Aydın, Balıkesir, Manisa illeri ve Ege Denizi ve Ege Adaları ile çevrilidir. İzmir, uzun ve dar bir körfezin başında yer almaktadır. İzmir Limanı, Türkiye'nin en büyük yedinci limanıdır. İzmir'in batısında denizi, plajları ve termal merkezleriyle Urla Yarımadası uzanır. Şehir, her yıl İzmir Enternasyonal Fuarı'nı düzenleyen önemli bir fuar merkezidir.",
    more: "https://tr.wikipedia.org/wiki/%C4%B0zmir",
  },
  {
    id: 14,
    name: "Kayseri",
    img: "https://i.hurimg.com/i/hdn/75/0x0/5a3f94cec9de3d0914b295bd.jpg",
    desc: "Kayseri , Türkiye'nin bir ilidir. Türkiye'nin toplam nüfus bakımından en kalabalık 14. şehri olup yüzölçümü olarak Türkiye'nin en büyük 8. ilidir. İç Anadolu’nun büyük ticaret ve sanayi merkezidir. Kayseri komşu illeri arasında; Niğde, Sivas, Adana, Yozgat, Kahramanmaraş ve Nevşehir yer almaktadır. Akkışla, Bünyan, Develi, Hacılar, İncesu, Kocasinan, Melikgazi, Pınarbaşı, Sarıoğlan, Sarız, Tomarza, Yahyalı, Talas, Özvatan, Felahiye ve Yeşilhisar olmak üzere 16 ilçeden oluşmaktadır. Orta Kızılırmak Bölümünde, Erciyes Dağı'nın eteklerinde bir ildir. Kuzey ve kuzeybatıda Yozgat, kuzey ve kuzeydoğuda Sivas, doğuda Kahramanmaraş, güneyde Adana, güneybatıda Niğde, batıda ise Nevşehir illeriyle çevrilidir. Dünyanın en eski şehirlerinden biri olan Kayseri (eski Mazaka, Ermenice: Մաժաք Mažak), klasik çağlarda Kapadokya adı verilen bölgededir. Kızılırmak'ın güneyinde bulunan bu bölge, Tuz Gölü'nden Fırat Nehri' ne kadar uzanır. İpek Yolu buradan geçer. Bölge, pek çok uygarlığın beşiği olmuştur.",
    more: "https://tr.wikipedia.org/wiki/Kayseri",
  },
  {
    id: 15,
    name: "Konya",
    img: "https://blog.turkishairlines.com/wp-content/uploads/2022/02/konya-gezilecek-yerler.jpg",
    desc: "Konya, Türkiye'nin yüzölçümü bakımından en büyük ili ve en kalabalık altıncı şehridir. 31 ilçeden oluşur. Konya il nüfusu 2021 yılında 2.277.017'ydi, trafik plaka numarası 42'dir. 1875'te kurulan Konya Belediyesi, 1987'de çıkarılan 3399 sayılı yasa gereğince 'büyükşehir' statüsüne kavuşmuş olup 1989'dan beri belediye hizmetleri bu statüye göre yürütülmektedir. 2014'te 6360 sayılı kanun ile büyükşehir belediyesinin sınırları il mülki sınırları oldu.    Ekonomik açıdan Türkiye'nin gelişmiş kentlerinden biri olan Konya doğal ve tarihsel zenginlikleriyle de önem taşır. Dünyanın en eski yerleşimlerinden biri olan Çatalhöyük, 2012 yılında UNESCO Dünya Miras Listesi'ne alınmıştır. Şehir Anadolu Selçukluları’nın ve Karamanoğulları’nın başkentliğini yapmıştır. Türkiye'nin en önemli sanayi kentlerinden birisidir. Anadolu Kaplanları'ndandır. Şehrin futbol takımı Konyaspor'dur. Yöresel yemekleri etliekmek, bamya çorbası, Mevlana böreği, yağ somunu, tirit, Konya pilavı, sac arası ve fırın kebabı'dır. Konya’nın simgeleri Mevlana Müzesi (Kubbe-i Hadrâ), çift başlı kartal'dır.",
    more: "https://tr.wikipedia.org/wiki/Konya",
  },
  {
    id: 16,
    name: "Edirne",
    img: "https://www.renktravel.com/wp-content/uploads/2020/12/Edirne-selimiye-mosque-2.jpg",
    desc: "Edirne Türkiye'nin Edirne ilinde yer alan şehir ve aynı ilin merkez ilçesi. Marmara Bölgesi'nin Trakya kesiminde, Yunanistan ve Bulgaristan sınırında yer almaktadır. Edirne, 1363'den 1453'e kadar Osmanlı İmparatorluğu'nun başkentiydi. 2020 sayımına göre toplam nüfusu 180.901'dir. Şehir Roma İmparatoru Hadrianus tarafından kuruldu ve Hadrianopolis adını aldı. Daha önce Uskudama adında eski bir Trak yerleşimiydi. Osmanlı dönemi'ndeki adı Edrine (ادرنه) yunanca adından türetildi. İngilizcede Adrianople olarak yazılır, 1928'deki Türk harf devrimi'nin ardından Edirne uluslararası alanda kabul edilen yeni adı olmuştur.",
    more: "https://tr.wikipedia.org/wiki/Edirne",
  },
  {
    id: 17,
    name: "Denizli",
    img: "https://www.anadolujet.com/documents/sehir_rehberi/denizli-genel.jpg",
    desc: "Denizli, Türkiye'de Ege Bölgesi'nde yer alan bir ildir. Nüfusu 2021 yılı itibarıyla 1.051.056'dir. 678.779 Merkezî nüfusu ile Ege Bölgesi'nde İzmir'den sonra ikinci Büyükşehir'dir. Tekstil sanayi, metal, gıda ürünleri ve yöreye has Denizli horozu ile meşhurdur. Anadolu Yarımadası'nın güneybatı, Ege Bölgesi'nin güneydoğusunda yer alır. Ege ve Akdeniz Bölgeleri arasında bir geçit durumundadır. Denizli ilinin her iki bölge üzerinde de toprakları vardır. Denizli ili 28° 38' - 30° 05' doğu meridyenleri (doğu uç noktası; Çivril ilçesi Gümüşsu - Gökgöl Köyü, Dinar sınırında Efekli Tepe, batı uç Aydın, Manisa; güneyde Muğla; kuzeyde Uşak illeri ile komşudur.) Yüzölçümü 12.134 km², denizden yüksekliği ise 209 m'dir.",
    more: "https://tr.wikipedia.org/wiki/Denizli",
  },
  {
    id: 18,
    name: "Van",
    img: "https://i20.haber7.net/resize/1300x731//haber/haber7/photos/2022/04/van_nerede_vanda_gezilecek_yerler_nerelerdir_vana_nasil_gidilir_1643198912_459.jpg",
    desc: "Van, Türkiye'nin bir ili ve en kalabalık on dokuzuncu şehri. Doğu Anadolu Bölgesi, Yukarı Murat-Van Bölümü'nde yer alır. Van ili nüfus bakımından bu bölgenin en büyük ilidir. 2021 sonu itibarıyla nüfusu 1.141.015 kişidir. Kuzeyden Ağrı, batıdan Bitlis, güneybatıdan Siirt, güneyden Hakkâri illeriyle, doğudan da İran'la sınırlıdır. Anadolu'nun en büyük kapalı havzası olan Van Gölü kıyısında toprakları verimli, akarsuları bol, iklim koşulları oldukça elverişli bir yerleşim merkezidir. Dünya'nın hâlâ yaşanılan en eski kentlerinden biridir.",
    more: "https://tr.wikipedia.org/wiki/Van",
  },
  {
    id: 19,
    name: "Çanakkale",
    img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/12/5a/dd/canakkale-truva-heykeli.jpg?w=600&h=400&s=1",
    desc: "Çanakkale, Türkiye'nin Çanakkale ilinin merkez ilçesidir. Anadolu'nun kuzeybatısında, Çanakkale Boğazı'nın güneydoğusunda yer alır. Nüfusu 2021 yılına göre 195,439 kişidir. Çanakkale'nin şu anki bulunduğu yerin adı 19. yüzyılda Kale-i Sultaniye olarak geçmektedir ve bu isim 1890 yılında şehrin resmî adı olarak kayıtlara geçmiştir. Çanakkale Osmanlı zamanında önemli bir kale işlevi görmüş olup, Kale-i Sultaniye (Osmanlı Türkçesi: قلعة سلطانيه) ya da günümüz Türkçesi ile Sultaniye Kalesi ismi bu işlevin bir kanıtıdır. 17. yüzyılın sonlarından itibaren gelişen çömlek yapımı, şehrin bu konuda ün yapmasını sağlamıştır. Hatta yine bu zamanlarda bir seyyahın yapılan seramiğin kalitesinden etkilenip, bunu Hollanda'nın Delft şehrinde yapılan seramiklerle karşılaştırması şehre Çanak kalesi ismini vermiştir. Çanakkale isminin Yunanca'sı Δαρδανέλλια veya Dardanellia, ki bu isim de sonradan Dardanelles olarak İngilizceye çevrilmiştir. 1920'lerden itibaren İngilizler Çanakkale'ye Chanak veya Kale Sultanie demeye başladılar.",
    more: "https://tr.wikipedia.org/wiki/%C3%87anakkale",
  },
  {
    id: 20,
    name: "Samsun",
    img: "https://iaysr.tmgrup.com.tr/5c0960/780/411/0/125/1024/663?u=https://iysr.tmgrup.com.tr/2022/09/14/karadenizin-incisi-samsun-1663171659842.jpeg",
    desc: "Samsun, Türkiye'nin büyükşehir statüsündeki otuz ilinden biridir. Karadeniz Bölgesi'ndeki Orta Karadeniz Bölümü'nde, Türkiye coğrafyasının en kuzeyinde merkezî bir noktada yer alır. On yedi ilçesi ve 1.247 mahallesi bulunan Samsun, 1.371.274 kişilik nüfusuyla bölgenin en yüksek, Türkiye'nin ise on altıncı en yüksek nüfuslu ilidir. Doğusunda Ordu, güneyinde Tokat ve Amasya, batısında ise Çorum ve Sinop illeri ile çevrili olup kuzeyinde Karadeniz bulunur. Karadeniz Bölgesi'nin eğitim, sağlık, sanayi, ticaret, ulaşım ve ekonomi açılarından en gelişmiş şehri olan Samsun kalkınmada birinci derecede öncelikli yörelerden biridir.",
    more: "https://tr.wikipedia.org/wiki/Samsun",
  },
];

export default data